apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-setup
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hl-cu
  source:
    repoURL: https://github.com/achrovisual/hl-k3s
    path: charts/private/metallb-setup
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
