apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  GH_API_TOKEN: {{ .Values.github.apiToken }}
  GH_USERNAME: {{ .Values.github.username }}
