apiVersion: v1
kind: Secret
metadata:
  name: cert-manager
  namespace: argo-cd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: cert-manager
  url: quay.io/jetstack/charts
  enableOCI: "true"
  type: helm