apiVersion: v1
kind: Secret
metadata:
  name: nginx
  namespace: argo-cd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: nginx
  url: https://kubernetes.github.io/ingress-nginx
  type: helm
