apiVersion: v1
kind: Secret
metadata:
  name: open-webui
  namespace: argo-cd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://helm.openwebui.com/
  project: hl-cu
  name: open-webui
  type: helm
