apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ printf "%s-l2" .Values.addressPool.name }}
  namespace: "{{ .Values.namespace }}"
spec:
  ipAddressPools:
  - "{{ .Values.addressPool.name }}"