argo-cd:
  nameOverride: argo-cd
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure
    service:
      type: ClusterIP
  configs:
    params:
      server:
        insecure: true
service:
  port: 80
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  className: nginx
  # Replace with your desired hostname
  host: argo-cd.your-domain.com