argo-cd:
  nameOverride: argo-cd
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure
    service:
      type: NodePort
  configs:
    params:
      server:
        insecure: true