ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  className: nginx
  # Replace with your desired hostname
  host: penpot.your-domain.com