argo-cd:
  nameOverride: argo-cd
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure
    ingress:
      enabled: true
      hostname: lab.achrovisual.io
      path: /argo-cd
  configs:
    params:
      server:
        insecure: true