open-webui:
  ollama:
    enabled: false
  pipelines:
    enabled: false
  ollamaUrls: []
  # Populate when pointing Open WebUI at an existing Ollama instance, e.g.:
  # - http://ollama.ollama-namespace.svc.cluster.local:11434
service:
  port: 80