open-webui:
  ingress:
    enabled: true
    class: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: lets-encrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    host: "open-webui.achrovisual.net"
    tls: true
  extraEnv:
  - name: OLLAMA_BASE_URL
    value: "http://{{ .Values.ollamaHostIp }}:11434"