base-template:
  monitoring:
    logs:
      enabled: true
  image:
    repository: ghcr.io/achrovisual/portfolio
    tag: sha-94e186bc88cdea2cb7aa4b74e455ab621ce7476d
    pullPolicy: IfNotPresent
  service:
    port: 3000
    type: LoadBalancer
  env:
    secretEnv:
      enabled: true
      name: github-credentials
      mappings:
        GH_API_TOKEN: GH_API_TOKEN
        GH_USERNAME: GH_USERNAME
