base-template:
  fullnameOverride: portfolio
  monitoring:
    logs:
      enabled: true
  image:
    repository: ghcr.io/achrovisual/portfolio
    tag: sha-875f9d30d6c352be935315806bca5bc012a28986
    pullPolicy: IfNotPresent
  service:
    port: 3000
    type: ClusterIP
  env:
    secretEnv:
      enabled: true
      name: github-credentials
      mappings:
        GH_API_TOKEN: GH_API_TOKEN
        GH_USERNAME: GH_USERNAME
  livenessProbe:
    httpGet:
      path: /api/status
      port: 3000
    initialDelaySeconds: 20
    periodSeconds: 300
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /api/status
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 300
    timeoutSeconds: 3
    failureThreshold: 1
