base-template:
  monitoring:
    logs:
      enabled: true
  image:
    repository: ghcr.io/achrovisual/portfolio
    tag: sha-ec295c4864354ceebd3a090ff9604a185f61b428
    pullPolicy: IfNotPresent
  service:
    port: 3000
    type: LoadBalancer
  env:
    secretEnv:
      enabled: true
      name: github-credentials
      mappings:
        GH_API_TOKEN: GH_API_TOKEN
        GH_USERNAME: GH_USERNAME
