base-template:
  fullnameOverride: portfolio
  monitoring:
    logs:
      enabled: true
  image:
    repository: ghcr.io/achrovisual/portfolio
    tag: sha-0b725e9ff1237360d37e4eb9f63b02831cb699b0
    pullPolicy: IfNotPresent
  service:
    port: 3000
    type: ClusterIP
  env:
    secretEnv:
      enabled: true
      name: github-credentials
      mappings:
        GH_API_TOKEN: GH_API_TOKEN
        GH_USERNAME: GH_USERNAME
  livenessProbe:
    httpGet:
      path: /api/status
      port: 3000
    initialDelaySeconds: 20
    periodSeconds: 300
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /api/status
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 300
    timeoutSeconds: 3
    failureThreshold: 1
github:
  username: <GITHUB_USERNAME> # Required: The GitHub account username.
  apiToken: <GITHUB_API_TOKEN> # Required: The GitHub API token.
service:
  port: 3000
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  className: nginx
  # Replace with your desired hostname
  host: portfolio.your-domain.com
  