base-template:
  monitoring:
    logs:
      enabled: true
  image:
    repository: ghcr.io/achrovisual/portfolio
    tag: sha-f83eaab10bf67a636da24f8b0bdcb5d31214a2c0
    pullPolicy: IfNotPresent
  service:
    port: 3000
    type: LoadBalancer
  secretEnv:
    enabled: true
    name: github-credentials
    mappings:
      GH_API_TOKEN: GH_API_TOKEN
      GITHUB_USERNAME: GITHUB_USERNAME
