apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hl-dev
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: {{ .Values.clusters.dev.server }}
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'