apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hl-dev
  source:
    repoURL: https://github.com/achrovisual/hl-k3s
    path: charts/private/cert-manager
    targetRevision: HEAD
  destination:
    server: {{ .Values.clusters.dev.server }}
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
