apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hl-dev
  source:
    repoURL: https://github.com/achrovisual/hl-k3s
    path: charts/private/open-webui
    targetRevision: feature/set-up-open-webui
  destination:
    server: {{ .Values.clusters.dev.server }}
    namespace: open-webui
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
