apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector-dev
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: hl-dev
  source:
    repoURL: https://github.com/achrovisual/hl-k3s
    path: charts/private/otel-collector
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: {{ .Values.clusters.dev.server }}
    namespace: otel-collector
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
