apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hl-dev
  source:
    repoURL: https://github.com/achrovisual/hl-k3s
    path: charts/private/portfolio
    targetRevision: feature/dev-cluster-nginx
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: {{ .Values.clusters.dev.server }}
    namespace: achrovisual
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

