apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: "{{ .Values.addressPool.name }}"
  namespace: "{{ .Values.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  addresses:
  - "{{ .Values.addressPool.ipRange }}"